---
title: "stepwise"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# removing Dalc
library(MASS)
library(tidyverse)
students <- read_csv("student-mat-recoded.csv", show_col_types=FALSE)
students <- students %>%
  select(-Dalc) %>% 
  mutate(Walc=case_when(Walc=="very low" ~ 1, 
                        Walc=="low" ~ 2, 
                        Walc=="moderate" ~ 3,
                        Walc=="high" ~ 4, 
                        Walc=="very high" ~ 5))
# fitting all regressions
full.lm <- lm(Walc~., data=students)
null.lm <- lm(Walc~1, data=students)
full.polr <- polr(as.factor(Walc)~., data=students)
null.polr <- polr(as.factor(Walc)~1, data=students)
```
# Linear Regression

### Original

```{r}
# rounding predictions to whole number 
lm.predict <- students %>% mutate(predict=round(predict(full.lm), 0))
# calculating accuracy by equating predictions to Walc
lm.predict %>% 
  mutate(equate=Walc==predict) %>% 
  summarize(accuracy=mean(equate)) 
# RSS of the linear model
sum(full.lm$residuals^2)
# RSS of the linear model after rounding the predictions
lm.predict %>% 
  mutate(diff=predict-Walc) %>% 
  summarize(RSS=sum(diff^2))
```

### Stepwise

```{r}
# performing stepwise
fw.lm <- step(null.lm, scope=formula(full.lm), direction="forward", trace=0)
bw.lm <- step(full.lm, direction="backward", trace=0)
summary(fw.lm)
summary(bw.lm)
```
```{r}
# rounding predictions to whole number 
fw.lm.predict <- students %>% mutate(predict=round(predict(fw.lm), 0))
# calculating accuracy by equating predictions to Walc
fw.lm.predict %>% 
  mutate(equate=Walc==predict) %>% 
  summarize(accuracy=mean(equate)) 
# RSS of the linear model
sum(fw.lm$residuals^2)
# RSS of the linear model after rounding 
fw.lm.predict %>% 
  mutate(diff=predict-Walc) %>% 
  summarize(RSS.rounded=sum(diff^2))
```
# Ordinal Logistic Regression

### Original

```{r}
# getting predicted probabilities
predict.prob <- predict(full.polr, type="probs")
# finding max probabilities
maxes <- c()
for (i in 1:nrow(students)){
  one <- predict.prob[i,][1]
  two <- predict.prob[i,][2]
  three <- predict.prob[i,][3]
  four <- predict.prob[i,][4]
  five <- predict.prob[i,][5]
  max <- c(1, 2, 3, 4, 5)[which.max(c(one, two, three, four, five))]
  maxes[i] <- max
}
polr.predict <- students %>% mutate(predict=maxes)
# finding accuracy by equating predictions and Walc
polr.predict %>% 
  mutate(equate=Walc==predict) %>% 
  summarize(accuracy=mean(equate)) 
# RSS of the ordinal logistic model
polr.predict %>% 
  mutate(diff=predict-Walc) %>% 
  summarize(RSS=sum(diff^2))
```
### Stepwise

```{r}
fw.polr <- step(null.polr, scope=formula(full.polr), direction="forward", trace=0)
bw.polr <- step(full.polr, direction="backward", trace=0)
summary(fw.polr)
summary(bw.polr)
```
##### Forward

```{r}
# getting predicted probabilities
predict.prob.fw <- predict(fw.polr, type="probs")
# finding max probabilities
maxes.fw <- c()
for (i in 1:nrow(students)){
  one <- predict.prob.fw[i,][1]
  two <- predict.prob.fw[i,][2]
  three <- predict.prob.fw[i,][3]
  four <- predict.prob.fw[i,][4]
  five <- predict.prob.fw[i,][5]
  max <- c(1, 2, 3, 4, 5)[which.max(c(one, two, three, four, five))]
  maxes.fw[i] <- max
}
fw.polr.predict <- students %>% mutate(predict=maxes.fw)
# finding accuracy by equating predictions and Walc
fw.polr.predict %>% 
  mutate(equate=Walc==predict) %>% 
  summarize(accuracy=mean(equate)) 
# RSS of the ordinal logistic model
fw.polr.predict %>% 
  mutate(diff=predict-Walc) %>% 
  summarize(RSS=sum(diff^2))
```
##### Backward

```{r}
# getting predicted probabilities
predict.prob.bw <- predict(bw.polr, type="probs")
# finding max probabilities
maxes.bw <- c()
for (i in 1:nrow(students)){
  one <- predict.prob.bw[i,][1]
  two <- predict.prob.bw[i,][2]
  three <- predict.prob.bw[i,][3]
  four <- predict.prob.bw[i,][4]
  five <- predict.prob.bw[i,][5]
  max <- c(1, 2, 3, 4, 5)[which.max(c(one, two, three, four, five))]
  maxes.bw[i] <- max
}
bw.polr.predict <- students %>% mutate(predict=maxes.bw)
# finding accuracy by equating predictions and Walc
bw.polr.predict %>% 
  mutate(equate=Walc==predict) %>% 
  summarize(accuracy=mean(equate)) 
# RSS of the ordinal logistic model
bw.polr.predict %>% 
  mutate(diff=predict-Walc) %>% 
  summarize(RSS=sum(diff^2))
```
